# Generated by Django 6.0.2 on 2026-02-10 05:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_qr_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('sports', 'Sports'), ('concert', 'Concert'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='MovieShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('available_tickets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('event', models.ForeignKey(limit_choices_to={'event_type': 'movie'}, on_delete=django.db.models.deletion.CASCADE, related_name='show_times', to='events.event')),
            ],
            options={
                'verbose_name': 'Movie Show Time',
                'verbose_name_plural': 'Movie Show Times',
                'ordering': ['show_date', 'start_time'],
                'unique_together': {('event', 'show_date', 'start_time')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='show_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='events.movieshowtime'),
        ),
    ]
